version: '3.8'
services:

  app:
    build: .
    container_name: app
    ports:
      - "5000:5000"
    volumes:
      - .:/home/node/app

  mysql:
    image: mysql:8.0
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: nestjs
      MYSQL_PASSWORD: password
    ports:
      - '33010:3306'
    volumes:
      - ./.docker/.data/mysql_data:/var/lib/mysql
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'

  rabbitmq:
    image: 'rabbitmq:3.8-management-alpine'
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - '15672:15672'
      - '5672:5672'
    volumes:
      - './.docker/.data/rabbitmq_data:/var/lib/rabbitmq/mnesia'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass redis_password
    volumes: 
      - ./.docker/.data/redis_data:/data
    extra_hosts:
        - 'host.docker.internal:172.17.0.1'